# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_exp_alterar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(847, 539)
        MainWindow.setStyleSheet("\n"
"QMainWindow, QWidget {\n"
"    background-color: #f4f6f9;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #e3e6ea;\n"
"    border-radius: 6px;\n"
"    gridline-color: transparent;\n"
"    alternate-background-color: #f8fafc;\n"
"    selection-background-color: #dbe9ff;\n"
"    selection-color: #000000;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 4px 8px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f1f3f6;\n"
"    border: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #f4f6f9;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_cabecalho = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_cabecalho.sizePolicy().hasHeightForWidth())
        self.widget_cabecalho.setSizePolicy(sizePolicy)
        self.widget_cabecalho.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_cabecalho.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_cabecalho.setStyleSheet("#widget_cabecalho {\n"
"    background-color: rgb(0, 64, 135);\n"
"    border: 1px solid #cfd8dc;\n"
"    border-radius: 10px;\n"
"}")
        self.widget_cabecalho.setObjectName("widget_cabecalho")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_cabecalho)
        self.horizontalLayout.setContentsMargins(15, 6, 15, 6)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.widget_cabecalho)
        self.frame.setMinimumSize(QtCore.QSize(150, 0))
        self.frame.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame.setStyleSheet("QFrame {\n"
"    background: white;\n"
"    border: 1px solid #cfd8dc;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLabel {\n"
"    border: none;\n"
"    background: transparent;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setContentsMargins(10, 2, 10, 2)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_3 = QtWidgets.QWidget(self.frame)
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(2)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(85, 85, 85);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_21.addWidget(self.label_6)
        self.line_Num_Exp = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_Num_Exp.sizePolicy().hasHeightForWidth())
        self.line_Num_Exp.setSizePolicy(sizePolicy)
        self.line_Num_Exp.setMinimumSize(QtCore.QSize(0, 25))
        self.line_Num_Exp.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.line_Num_Exp.setFont(font)
        self.line_Num_Exp.setStyleSheet("color: #2563eb;\n"
"border: none;\n"
"background: transparent;")
        self.line_Num_Exp.setInputMask("")
        self.line_Num_Exp.setText("")
        self.line_Num_Exp.setFrame(True)
        self.line_Num_Exp.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_Num_Exp.setAlignment(QtCore.Qt.AlignCenter)
        self.line_Num_Exp.setDragEnabled(False)
        self.line_Num_Exp.setReadOnly(False)
        self.line_Num_Exp.setPlaceholderText("")
        self.line_Num_Exp.setObjectName("line_Num_Exp")
        self.verticalLayout_21.addWidget(self.line_Num_Exp)
        self.horizontalLayout_6.addWidget(self.widget_3)
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #2563eb;\n"
"border: none;\n"
"background: transparent;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.horizontalLayout.addWidget(self.frame)
        self.label_13 = QtWidgets.QLabel(self.widget_cabecalho)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 64, 135);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.label_4 = QtWidgets.QLabel(self.widget_cabecalho)
        self.label_4.setMinimumSize(QtCore.QSize(30, 0))
        self.label_4.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white;\n"
"font-size: 18px;\n"
"border: none;\n"
"background: transparent;")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_7 = QtWidgets.QLabel(self.widget_cabecalho)
        self.label_7.setMinimumSize(QtCore.QSize(85, 0))
        self.label_7.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label_7.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"font-size: 10px;\n"
"border: none;\n"
"background: transparent;")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.frame_2 = QtWidgets.QFrame(self.widget_cabecalho)
        self.frame_2.setMinimumSize(QtCore.QSize(110, 35))
        self.frame_2.setMaximumSize(QtCore.QSize(110, 35))
        self.frame_2.setStyleSheet("#frame_2 {\n"
"    background: white;\n"
"    border-radius: 6px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_11.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_11.setSpacing(8)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.date_Emissao = QtWidgets.QDateEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_Emissao.sizePolicy().hasHeightForWidth())
        self.date_Emissao.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date_Emissao.setFont(font)
        self.date_Emissao.setStyleSheet("QDateEdit {\n"
"    border: none;\n"
"    background: transparent;\n"
"    padding-left: 4px;\n"
"    font-size: 10pt;\n"
"    color: rgb(61, 61, 61);\n"
"}\n"
"\n"
"/* MÊS E ANO */\n"
"QCalendarWidget QToolButton {\n"
"    color: black;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* fundo da barra superior */\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar {\n"
"    background-color: white;\n"
"}")
        self.date_Emissao.setCalendarPopup(True)
        self.date_Emissao.setObjectName("date_Emissao")
        self.horizontalLayout_11.addWidget(self.date_Emissao)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.widget_cabecalho)
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_6.setStyleSheet("background-color: #f4f6f9;")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_22.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_22.setSpacing(3)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_64 = QtWidgets.QLabel(self.widget_6)
        self.label_64.setMinimumSize(QtCore.QSize(100, 0))
        self.label_64.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setStyleSheet("border: none;\n"
"background: transparent;\n"
"color: #5f6b7a;\n"
"font-size: 9px;\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.label_64.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_64.setObjectName("label_64")
        self.verticalLayout_22.addWidget(self.label_64)
        self.combo_Operacao = QtWidgets.QComboBox(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_Operacao.sizePolicy().hasHeightForWidth())
        self.combo_Operacao.setSizePolicy(sizePolicy)
        self.combo_Operacao.setMinimumSize(QtCore.QSize(0, 34))
        self.combo_Operacao.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.combo_Operacao.setFont(font)
        self.combo_Operacao.setStyleSheet("#combo_Operacao {\n"
"    border: 1px solid #e5e7eb;\n"
"    border-radius: 6px;\n"
"    padding-left: 10px;\n"
"    background: white;\n"
"    min-height: 32px;\n"
"    font-size: 11px;\n"
"    color: #374151;\n"
"}")
        self.combo_Operacao.setObjectName("combo_Operacao")
        self.combo_Operacao.addItem("")
        self.verticalLayout_22.addWidget(self.combo_Operacao)
        self.verticalLayout.addWidget(self.widget_6)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout.addWidget(self.frame_5)
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_5)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.widget_4)
        self.widget.setMinimumSize(QtCore.QSize(0, 46))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 46))
        self.widget.setStyleSheet("background-color: #f4f6f9;")
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(10, 6, 10, 6)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setMinimumSize(QtCore.QSize(45, 0))
        self.label_8.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border: none;\n"
"background: transparent;\n"
"color: #5f6b7a;\n"
"font-size: 9px;\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.combo_Cliente_Vendas = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_Cliente_Vendas.sizePolicy().hasHeightForWidth())
        self.combo_Cliente_Vendas.setSizePolicy(sizePolicy)
        self.combo_Cliente_Vendas.setMinimumSize(QtCore.QSize(0, 34))
        self.combo_Cliente_Vendas.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.combo_Cliente_Vendas.setFont(font)
        self.combo_Cliente_Vendas.setStyleSheet("#combo_Cliente_Vendas {\n"
"    border: 1px solid #e5e7eb;\n"
"    border-radius: 6px;\n"
"    padding-left: 10px;\n"
"    background: white;\n"
"    min-height: 32px;\n"
"    font-size: 11px;\n"
"    color: #374151;\n"
"}")
        self.combo_Cliente_Vendas.setObjectName("combo_Cliente_Vendas")
        self.horizontalLayout_4.addWidget(self.combo_Cliente_Vendas)
        self.verticalLayout_2.addWidget(self.widget)
        self.frame_7 = QtWidgets.QFrame(self.widget_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2.addWidget(self.frame_7)
        self.groupBox = QtWidgets.QGroupBox(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("#groupBox {\n"
"    border: none;\n"
"    margin-top: 18px;\n"
"    font-weight: bold;\n"
"    color: #5f6b7a;\n"
"font-size: 9px;\n"
"}\n"
"\n"
"#groupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 12px;\n"
"    padding: 0 6px 0 6px;\n"
"padding-left: 2px;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.table_Vendas_Pendentes = QtWidgets.QTableWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_Vendas_Pendentes.sizePolicy().hasHeightForWidth())
        self.table_Vendas_Pendentes.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.table_Vendas_Pendentes.setFont(font)
        self.table_Vendas_Pendentes.setStyleSheet("#table_Vendas_Pendentes {\n"
"    background-color: white;\n"
"    border: 1px solid #e3e6ea;\n"
"    border-radius: 6px;\n"
"    gridline-color: transparent;\n"
"    alternate-background-color: #f8fafc;\n"
"    selection-background-color: #dbe9ff;\n"
"    selection-color: #000000;\n"
"}\n"
"\n"
"QTableWidget#table_Vendas_Pendentes QHeaderView::section {\n"
"    background-color: #f1f3f6;\n"
"    border: none;\n"
"}")
        self.table_Vendas_Pendentes.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_Vendas_Pendentes.setAlternatingRowColors(True)
        self.table_Vendas_Pendentes.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_Vendas_Pendentes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_Vendas_Pendentes.setShowGrid(False)
        self.table_Vendas_Pendentes.setObjectName("table_Vendas_Pendentes")
        self.table_Vendas_Pendentes.setColumnCount(8)
        self.table_Vendas_Pendentes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_Vendas_Pendentes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Vendas_Pendentes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_Vendas_Pendentes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Vendas_Pendentes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_Vendas_Pendentes.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_Vendas_Pendentes.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Vendas_Pendentes.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Vendas_Pendentes.setHorizontalHeaderItem(7, item)
        self.verticalLayout_4.addWidget(self.table_Vendas_Pendentes)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("#groupBox_2 {\n"
"    border: none;\n"
"    margin-top: 18px;\n"
"    font-weight: bold;\n"
"    color: #5f6b7a;\n"
"font-size: 9px;\n"
"}\n"
"\n"
"#groupBox_2::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 12px;\n"
"    padding: 0 6px 0 6px;\n"
"padding-left: 2px;\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_21 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_21.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_21.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget_21.setStyleSheet("")
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_37 = QtWidgets.QLabel(self.widget_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setMinimumSize(QtCore.QSize(65, 0))
        self.label_37.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("border: none;\n"
"background: transparent;\n"
"color: #5f6b7a;\n"
"font-size: 9px;\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.label_37.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_19.addWidget(self.label_37)
        self.line_LocalExp_Venda = QtWidgets.QLineEdit(self.widget_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_LocalExp_Venda.sizePolicy().hasHeightForWidth())
        self.line_LocalExp_Venda.setSizePolicy(sizePolicy)
        self.line_LocalExp_Venda.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line_LocalExp_Venda.setFont(font)
        self.line_LocalExp_Venda.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.line_LocalExp_Venda.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_LocalExp_Venda.setInputMask("")
        self.line_LocalExp_Venda.setText("")
        self.line_LocalExp_Venda.setFrame(True)
        self.line_LocalExp_Venda.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_LocalExp_Venda.setAlignment(QtCore.Qt.AlignCenter)
        self.line_LocalExp_Venda.setObjectName("line_LocalExp_Venda")
        self.horizontalLayout_19.addWidget(self.line_LocalExp_Venda)
        self.label = QtWidgets.QLabel(self.widget_21)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_19.addWidget(self.label)
        self.verticalLayout_7.addWidget(self.widget_21)
        self.table_Expedicao = QtWidgets.QTableWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_Expedicao.sizePolicy().hasHeightForWidth())
        self.table_Expedicao.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.table_Expedicao.setFont(font)
        self.table_Expedicao.setStyleSheet("#table_Expedicao {\n"
"    background-color: white;\n"
"    border: 1px solid #e3e6ea;\n"
"    border-radius: 6px;\n"
"    gridline-color: transparent;\n"
"    alternate-background-color: #f8fafc;\n"
"    selection-background-color: #dbe9ff;\n"
"    selection-color: #000000;\n"
"}\n"
"\n"
"QTableWidget#table_Expedicao QHeaderView::section {\n"
"    background-color: #f1f3f6;\n"
"    border: none;\n"
"}")
        self.table_Expedicao.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_Expedicao.setAlternatingRowColors(True)
        self.table_Expedicao.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_Expedicao.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_Expedicao.setShowGrid(False)
        self.table_Expedicao.setObjectName("table_Expedicao")
        self.table_Expedicao.setColumnCount(7)
        self.table_Expedicao.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_Expedicao.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Expedicao.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_Expedicao.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Expedicao.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_Expedicao.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.table_Expedicao.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Expedicao.setHorizontalHeaderItem(6, item)
        self.verticalLayout_7.addWidget(self.table_Expedicao)
        self.frame_6 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7.addWidget(self.frame_6)
        self.widget_27 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_27.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_27.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_27.setStyleSheet("background-color: #f4f6f9;")
        self.widget_27.setObjectName("widget_27")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.widget_27)
        self.horizontalLayout_34.setContentsMargins(15, 6, 15, 6)
        self.horizontalLayout_34.setSpacing(6)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.btn_Limpar = QtWidgets.QPushButton(self.widget_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Limpar.sizePolicy().hasHeightForWidth())
        self.btn_Limpar.setSizePolicy(sizePolicy)
        self.btn_Limpar.setMinimumSize(QtCore.QSize(90, 0))
        self.btn_Limpar.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Limpar.setFont(font)
        self.btn_Limpar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Limpar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_Limpar.setAutoFillBackground(False)
        self.btn_Limpar.setStyleSheet("QPushButton {\n"
"    background: #f5f7fa;\n"
"    border: 1px solid #cfd6e0;\n"
"    border-radius: 4px;\n"
"    padding: 6px 12px;\n"
"    color: #2c3e50;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #e9edf3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #dfe5ec;\n"
"}")
        self.btn_Limpar.setCheckable(False)
        self.btn_Limpar.setAutoDefault(False)
        self.btn_Limpar.setDefault(False)
        self.btn_Limpar.setFlat(False)
        self.btn_Limpar.setObjectName("btn_Limpar")
        self.horizontalLayout_34.addWidget(self.btn_Limpar)
        self.label_5 = QtWidgets.QLabel(self.widget_27)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_34.addWidget(self.label_5)
        self.btn_Excluir_Expedicao = QtWidgets.QPushButton(self.widget_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Excluir_Expedicao.sizePolicy().hasHeightForWidth())
        self.btn_Excluir_Expedicao.setSizePolicy(sizePolicy)
        self.btn_Excluir_Expedicao.setMinimumSize(QtCore.QSize(90, 0))
        self.btn_Excluir_Expedicao.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Excluir_Expedicao.setFont(font)
        self.btn_Excluir_Expedicao.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Excluir_Expedicao.setStyleSheet("QPushButton {\n"
"    background: #f5f7fa;\n"
"    border: 1px solid #cfd6e0;\n"
"    border-radius: 4px;\n"
"    padding: 6px 6px;\n"
"    color: #2c3e50;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #e9edf3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #dfe5ec;\n"
"}")
        self.btn_Excluir_Expedicao.setObjectName("btn_Excluir_Expedicao")
        self.horizontalLayout_34.addWidget(self.btn_Excluir_Expedicao)
        self.label_2 = QtWidgets.QLabel(self.widget_27)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_34.addWidget(self.label_2)
        self.btn_Excluir_Item = QtWidgets.QPushButton(self.widget_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Excluir_Item.sizePolicy().hasHeightForWidth())
        self.btn_Excluir_Item.setSizePolicy(sizePolicy)
        self.btn_Excluir_Item.setMinimumSize(QtCore.QSize(90, 0))
        self.btn_Excluir_Item.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Excluir_Item.setFont(font)
        self.btn_Excluir_Item.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Excluir_Item.setStyleSheet("QPushButton {\n"
"    background: #f5f7fa;\n"
"    border: 1px solid #cfd6e0;\n"
"    border-radius: 4px;\n"
"    padding: 6px 6px;\n"
"    color: #2c3e50;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #e9edf3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #dfe5ec;\n"
"}")
        self.btn_Excluir_Item.setObjectName("btn_Excluir_Item")
        self.horizontalLayout_34.addWidget(self.btn_Excluir_Item)
        self.label_41 = QtWidgets.QLabel(self.widget_27)
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_34.addWidget(self.label_41)
        self.btn_Salvar = QtWidgets.QPushButton(self.widget_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Salvar.sizePolicy().hasHeightForWidth())
        self.btn_Salvar.setSizePolicy(sizePolicy)
        self.btn_Salvar.setMinimumSize(QtCore.QSize(90, 40))
        self.btn_Salvar.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Salvar.setFont(font)
        self.btn_Salvar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Salvar.setStyleSheet("QPushButton {\n"
"    background-color: #0d4a92;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 0 5px;\n"
"    font-size: 10pt;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1557a6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0a3b75;\n"
"}")
        self.btn_Salvar.setObjectName("btn_Salvar")
        self.horizontalLayout_34.addWidget(self.btn_Salvar)
        self.verticalLayout_7.addWidget(self.widget_27)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.widget_5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Projetos Engenharia"))
        self.label_6.setText(_translate("MainWindow", "Nº EXPEDIÇÃO"))
        self.label_3.setText(_translate("MainWindow", "📄"))
        self.label_13.setText(_translate("MainWindow", "EXPEDIÇÃO DE MATERIAIS"))
        self.label_4.setText(_translate("MainWindow", "📅"))
        self.label_7.setText(_translate("MainWindow", "DATA EMISSÃO"))
        self.label_64.setText(_translate("MainWindow", "TIPO OPERAÇÃO"))
        self.combo_Operacao.setItemText(0, _translate("MainWindow", "VENDAS"))
        self.label_8.setText(_translate("MainWindow", "CLIENTE"))
        self.groupBox.setTitle(_translate("MainWindow", "VENDAS PENDENTES"))
        item = self.table_Vendas_Pendentes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ORIGEM"))
        item = self.table_Vendas_Pendentes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CÓDIGO"))
        item = self.table_Vendas_Pendentes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DESCRIÇÃO"))
        item = self.table_Vendas_Pendentes.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "REFERÊNCIA"))
        item = self.table_Vendas_Pendentes.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "UM"))
        item = self.table_Vendas_Pendentes.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "QTDE"))
        item = self.table_Vendas_Pendentes.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "LOCAL"))
        item = self.table_Vendas_Pendentes.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "SALDO"))
        self.groupBox_2.setTitle(_translate("MainWindow", "EXPEDIÇÃO"))
        self.label_37.setText(_translate("MainWindow", "LOCAL EXP"))
        item = self.table_Expedicao.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "LOCAL EXP"))
        item = self.table_Expedicao.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CÓDIGO"))
        item = self.table_Expedicao.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DESCRIÇÃO"))
        item = self.table_Expedicao.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "REFERÊNCIA"))
        item = self.table_Expedicao.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "UM"))
        item = self.table_Expedicao.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "QTDE"))
        item = self.table_Expedicao.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "ORIGEM"))
        self.btn_Limpar.setText(_translate("MainWindow", "Limpar"))
        self.btn_Excluir_Expedicao.setText(_translate("MainWindow", "Excluir Exp."))
        self.btn_Excluir_Item.setText(_translate("MainWindow", "Excluir Item"))
        self.btn_Salvar.setText(_translate("MainWindow", "Salvar"))
