# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_exp_incluir_v3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(669, 495)
        MainWindow.setStyleSheet("\n"
"QMainWindow, QWidget {\n"
"    background-color: #f4f6f9;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #e3e6ea;\n"
"    border-radius: 6px;\n"
"    gridline-color: transparent;\n"
"    alternate-background-color: #f8fafc;\n"
"    selection-background-color: #dbe9ff;\n"
"    selection-color: #000000;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 4px 8px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f1f3f6;\n"
"    border: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #f4f6f9;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_cabecalho = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_cabecalho.sizePolicy().hasHeightForWidth())
        self.widget_cabecalho.setSizePolicy(sizePolicy)
        self.widget_cabecalho.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_cabecalho.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_cabecalho.setStyleSheet("#widget_cabecalho {\n"
"    background-color: rgb(0, 64, 135);\n"
"    border: 1px solid #cfd8dc;\n"
"    border-radius: 10px;\n"
"}")
        self.widget_cabecalho.setObjectName("widget_cabecalho")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_cabecalho)
        self.horizontalLayout.setContentsMargins(15, 6, 15, 6)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtWidgets.QLabel(self.widget_cabecalho)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 64, 135);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.verticalLayout.addWidget(self.widget_cabecalho)
        self.stacked_Responsavel = QtWidgets.QStackedWidget(self.centralwidget)
        self.stacked_Responsavel.setObjectName("stacked_Responsavel")
        self.page_Logistica = QtWidgets.QWidget()
        self.page_Logistica.setStyleSheet("background-color: #f4f6f9;")
        self.page_Logistica.setObjectName("page_Logistica")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_Logistica)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.page_Logistica)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_40 = QtWidgets.QWidget(self.widget)
        self.widget_40.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_40.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_40.setObjectName("widget_40")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.widget_40)
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.widget_13 = QtWidgets.QWidget(self.widget_40)
        self.widget_13.setMinimumSize(QtCore.QSize(160, 0))
        self.widget_13.setMaximumSize(QtCore.QSize(160, 16777215))
        self.widget_13.setStyleSheet("")
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_49 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_49.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_49.setSpacing(3)
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.label_75 = QtWidgets.QLabel(self.widget_13)
        self.label_75.setMinimumSize(QtCore.QSize(0, 0))
        self.label_75.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_75.setFont(font)
        self.label_75.setStyleSheet("border: none;\n"
"background: transparent;\n"
"color: #5f6b7a;\n"
"font-size: 9px;\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.label_75.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_75.setObjectName("label_75")
        self.verticalLayout_49.addWidget(self.label_75)
        self.combo_Tipo_Emb_Log = QtWidgets.QComboBox(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_Tipo_Emb_Log.sizePolicy().hasHeightForWidth())
        self.combo_Tipo_Emb_Log.setSizePolicy(sizePolicy)
        self.combo_Tipo_Emb_Log.setMinimumSize(QtCore.QSize(0, 25))
        self.combo_Tipo_Emb_Log.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.combo_Tipo_Emb_Log.setFont(font)
        self.combo_Tipo_Emb_Log.setStyleSheet("#combo_Tipo_Emb_Log {\n"
"    border: 1px solid #e5e7eb;\n"
"    border-radius: 6px;\n"
"    padding-left: 10px;\n"
"    background: white;\n"
"    font-size: 11px;\n"
"    color: #374151;\n"
"}")
        self.combo_Tipo_Emb_Log.setObjectName("combo_Tipo_Emb_Log")
        self.verticalLayout_49.addWidget(self.combo_Tipo_Emb_Log)
        self.horizontalLayout_35.addWidget(self.widget_13)
        self.widget_45 = QtWidgets.QWidget(self.widget_40)
        self.widget_45.setStyleSheet("")
        self.widget_45.setObjectName("widget_45")
        self.verticalLayout_55 = QtWidgets.QVBoxLayout(self.widget_45)
        self.verticalLayout_55.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_55.setSpacing(3)
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.label_82 = QtWidgets.QLabel(self.widget_45)
        self.label_82.setMinimumSize(QtCore.QSize(0, 0))
        self.label_82.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_82.setFont(font)
        self.label_82.setStyleSheet("border: none;\n"
"background: transparent;\n"
"color: #5f6b7a;\n"
"font-size: 9px;\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.label_82.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_82.setObjectName("label_82")
        self.verticalLayout_55.addWidget(self.label_82)
        self.line_Peso_Emb_Log = QtWidgets.QLineEdit(self.widget_45)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_Peso_Emb_Log.sizePolicy().hasHeightForWidth())
        self.line_Peso_Emb_Log.setSizePolicy(sizePolicy)
        self.line_Peso_Emb_Log.setMinimumSize(QtCore.QSize(0, 25))
        self.line_Peso_Emb_Log.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.line_Peso_Emb_Log.setFont(font)
        self.line_Peso_Emb_Log.setStyleSheet("color: #374151;\n"
"border: none;\n"
"background: white;")
        self.line_Peso_Emb_Log.setInputMask("")
        self.line_Peso_Emb_Log.setText("")
        self.line_Peso_Emb_Log.setFrame(True)
        self.line_Peso_Emb_Log.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_Peso_Emb_Log.setAlignment(QtCore.Qt.AlignCenter)
        self.line_Peso_Emb_Log.setDragEnabled(False)
        self.line_Peso_Emb_Log.setReadOnly(False)
        self.line_Peso_Emb_Log.setPlaceholderText("")
        self.line_Peso_Emb_Log.setObjectName("line_Peso_Emb_Log")
        self.verticalLayout_55.addWidget(self.line_Peso_Emb_Log)
        self.horizontalLayout_35.addWidget(self.widget_45)
        self.widget_60 = QtWidgets.QWidget(self.widget_40)
        self.widget_60.setStyleSheet("")
        self.widget_60.setObjectName("widget_60")
        self.verticalLayout_57 = QtWidgets.QVBoxLayout(self.widget_60)
        self.verticalLayout_57.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_57.setSpacing(3)
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.label_87 = QtWidgets.QLabel(self.widget_60)
        self.label_87.setMinimumSize(QtCore.QSize(0, 0))
        self.label_87.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_87.setFont(font)
        self.label_87.setStyleSheet("border: none;\n"
"background: transparent;\n"
"color: #5f6b7a;\n"
"font-size: 9px;\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.label_87.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_87.setObjectName("label_87")
        self.verticalLayout_57.addWidget(self.label_87)
        self.line_Peso_Total_Log = QtWidgets.QLineEdit(self.widget_60)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_Peso_Total_Log.sizePolicy().hasHeightForWidth())
        self.line_Peso_Total_Log.setSizePolicy(sizePolicy)
        self.line_Peso_Total_Log.setMinimumSize(QtCore.QSize(0, 25))
        self.line_Peso_Total_Log.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.line_Peso_Total_Log.setFont(font)
        self.line_Peso_Total_Log.setStyleSheet("color: #374151;\n"
"border: none;\n"
"background: white;")
        self.line_Peso_Total_Log.setInputMask("")
        self.line_Peso_Total_Log.setText("")
        self.line_Peso_Total_Log.setFrame(True)
        self.line_Peso_Total_Log.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_Peso_Total_Log.setAlignment(QtCore.Qt.AlignCenter)
        self.line_Peso_Total_Log.setDragEnabled(False)
        self.line_Peso_Total_Log.setReadOnly(False)
        self.line_Peso_Total_Log.setPlaceholderText("")
        self.line_Peso_Total_Log.setObjectName("line_Peso_Total_Log")
        self.verticalLayout_57.addWidget(self.line_Peso_Total_Log)
        self.horizontalLayout_35.addWidget(self.widget_60)
        self.btn_Add_Vol_Log = QtWidgets.QPushButton(self.widget_40)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Add_Vol_Log.sizePolicy().hasHeightForWidth())
        self.btn_Add_Vol_Log.setSizePolicy(sizePolicy)
        self.btn_Add_Vol_Log.setMinimumSize(QtCore.QSize(80, 34))
        self.btn_Add_Vol_Log.setMaximumSize(QtCore.QSize(80, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Add_Vol_Log.setFont(font)
        self.btn_Add_Vol_Log.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Add_Vol_Log.setStyleSheet("QPushButton {\n"
"    background-color: #0d4a92;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    min-height: 34px;\n"
"    padding: 0 5px;\n"
"    font-size: 9pt;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1557a6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0a3b75;\n"
"}")
        self.btn_Add_Vol_Log.setObjectName("btn_Add_Vol_Log")
        self.horizontalLayout_35.addWidget(self.btn_Add_Vol_Log)
        self.btn_Excluir_Vol_Log = QtWidgets.QPushButton(self.widget_40)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Excluir_Vol_Log.sizePolicy().hasHeightForWidth())
        self.btn_Excluir_Vol_Log.setSizePolicy(sizePolicy)
        self.btn_Excluir_Vol_Log.setMinimumSize(QtCore.QSize(80, 34))
        self.btn_Excluir_Vol_Log.setMaximumSize(QtCore.QSize(80, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Excluir_Vol_Log.setFont(font)
        self.btn_Excluir_Vol_Log.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Excluir_Vol_Log.setStyleSheet("QPushButton {\n"
"    background-color: #0d4a92;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    min-height: 34px;\n"
"    padding: 0 5px;\n"
"    font-size: 9pt;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1557a6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0a3b75;\n"
"}")
        self.btn_Excluir_Vol_Log.setObjectName("btn_Excluir_Vol_Log")
        self.horizontalLayout_35.addWidget(self.btn_Excluir_Vol_Log)
        self.verticalLayout_3.addWidget(self.widget_40)
        self.widget_62 = QtWidgets.QWidget(self.widget)
        self.widget_62.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_62.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_62.setObjectName("widget_62")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.widget_62)
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.widget_17 = QtWidgets.QWidget(self.widget_62)
        self.widget_17.setStyleSheet("")
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_58 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_58.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_58.setSpacing(3)
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.label_93 = QtWidgets.QLabel(self.widget_17)
        self.label_93.setMinimumSize(QtCore.QSize(0, 0))
        self.label_93.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_93.setFont(font)
        self.label_93.setStyleSheet("border: none;\n"
"background: transparent;\n"
"color: #5f6b7a;\n"
"font-size: 9px;\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.label_93.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_93.setObjectName("label_93")
        self.verticalLayout_58.addWidget(self.label_93)
        self.line_Altura_Log = QtWidgets.QLineEdit(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_Altura_Log.sizePolicy().hasHeightForWidth())
        self.line_Altura_Log.setSizePolicy(sizePolicy)
        self.line_Altura_Log.setMinimumSize(QtCore.QSize(0, 25))
        self.line_Altura_Log.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.line_Altura_Log.setFont(font)
        self.line_Altura_Log.setStyleSheet("color: #374151;\n"
"border: none;\n"
"background: white;")
        self.line_Altura_Log.setInputMask("")
        self.line_Altura_Log.setText("")
        self.line_Altura_Log.setFrame(True)
        self.line_Altura_Log.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_Altura_Log.setAlignment(QtCore.Qt.AlignCenter)
        self.line_Altura_Log.setDragEnabled(False)
        self.line_Altura_Log.setReadOnly(False)
        self.line_Altura_Log.setPlaceholderText("")
        self.line_Altura_Log.setObjectName("line_Altura_Log")
        self.verticalLayout_58.addWidget(self.line_Altura_Log)
        self.horizontalLayout_36.addWidget(self.widget_17)
        self.widget_63 = QtWidgets.QWidget(self.widget_62)
        self.widget_63.setStyleSheet("")
        self.widget_63.setObjectName("widget_63")
        self.verticalLayout_59 = QtWidgets.QVBoxLayout(self.widget_63)
        self.verticalLayout_59.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_59.setSpacing(3)
        self.verticalLayout_59.setObjectName("verticalLayout_59")
        self.label_95 = QtWidgets.QLabel(self.widget_63)
        self.label_95.setMinimumSize(QtCore.QSize(0, 0))
        self.label_95.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_95.setFont(font)
        self.label_95.setStyleSheet("border: none;\n"
"background: transparent;\n"
"color: #5f6b7a;\n"
"font-size: 9px;\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.label_95.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_95.setObjectName("label_95")
        self.verticalLayout_59.addWidget(self.label_95)
        self.line_Largura_Log = QtWidgets.QLineEdit(self.widget_63)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_Largura_Log.sizePolicy().hasHeightForWidth())
        self.line_Largura_Log.setSizePolicy(sizePolicy)
        self.line_Largura_Log.setMinimumSize(QtCore.QSize(0, 25))
        self.line_Largura_Log.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.line_Largura_Log.setFont(font)
        self.line_Largura_Log.setStyleSheet("color: #374151;\n"
"border: none;\n"
"background: white;")
        self.line_Largura_Log.setInputMask("")
        self.line_Largura_Log.setText("")
        self.line_Largura_Log.setFrame(True)
        self.line_Largura_Log.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_Largura_Log.setAlignment(QtCore.Qt.AlignCenter)
        self.line_Largura_Log.setDragEnabled(False)
        self.line_Largura_Log.setReadOnly(False)
        self.line_Largura_Log.setPlaceholderText("")
        self.line_Largura_Log.setObjectName("line_Largura_Log")
        self.verticalLayout_59.addWidget(self.line_Largura_Log)
        self.horizontalLayout_36.addWidget(self.widget_63)
        self.widget_64 = QtWidgets.QWidget(self.widget_62)
        self.widget_64.setStyleSheet("")
        self.widget_64.setObjectName("widget_64")
        self.verticalLayout_60 = QtWidgets.QVBoxLayout(self.widget_64)
        self.verticalLayout_60.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_60.setSpacing(3)
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self.label_96 = QtWidgets.QLabel(self.widget_64)
        self.label_96.setMinimumSize(QtCore.QSize(0, 0))
        self.label_96.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_96.setFont(font)
        self.label_96.setStyleSheet("border: none;\n"
"background: transparent;\n"
"color: #5f6b7a;\n"
"font-size: 9px;\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.label_96.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_96.setObjectName("label_96")
        self.verticalLayout_60.addWidget(self.label_96)
        self.line_Compr_Log = QtWidgets.QLineEdit(self.widget_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_Compr_Log.sizePolicy().hasHeightForWidth())
        self.line_Compr_Log.setSizePolicy(sizePolicy)
        self.line_Compr_Log.setMinimumSize(QtCore.QSize(0, 25))
        self.line_Compr_Log.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.line_Compr_Log.setFont(font)
        self.line_Compr_Log.setStyleSheet("color: #374151;\n"
"border: none;\n"
"background: white;")
        self.line_Compr_Log.setInputMask("")
        self.line_Compr_Log.setText("")
        self.line_Compr_Log.setFrame(True)
        self.line_Compr_Log.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_Compr_Log.setAlignment(QtCore.Qt.AlignCenter)
        self.line_Compr_Log.setDragEnabled(False)
        self.line_Compr_Log.setReadOnly(False)
        self.line_Compr_Log.setPlaceholderText("")
        self.line_Compr_Log.setObjectName("line_Compr_Log")
        self.verticalLayout_60.addWidget(self.line_Compr_Log)
        self.horizontalLayout_36.addWidget(self.widget_64)
        self.verticalLayout_3.addWidget(self.widget_62)
        self.groupBox_Log = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_Log.setFont(font)
        self.groupBox_Log.setStyleSheet("#groupBox_Log {\n"
"    border: none;\n"
"    margin-top: 18px;\n"
"    font-weight: bold;\n"
"    color: #5f6b7a;\n"
"font-size: 9px;\n"
"}\n"
"\n"
"#groupBox_Log::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 12px;\n"
"    padding: 0 6px 0 6px;\n"
"padding-left: 2px;\n"
"}")
        self.groupBox_Log.setObjectName("groupBox_Log")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_Log)
        self.verticalLayout_9.setContentsMargins(6, 6, 6, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.table_Volume_Log = QtWidgets.QTableWidget(self.groupBox_Log)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_Volume_Log.sizePolicy().hasHeightForWidth())
        self.table_Volume_Log.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.table_Volume_Log.setFont(font)
        self.table_Volume_Log.setStyleSheet("#table_Volume_Log {\n"
"    background-color: white;\n"
"    border: 1px solid #e3e6ea;\n"
"    border-radius: 6px;\n"
"    gridline-color: transparent;\n"
"    alternate-background-color: #f8fafc;\n"
"    selection-background-color: #dbe9ff;\n"
"    selection-color: #000000;\n"
"}\n"
"\n"
"QTableWidget#table_Volume_Log QHeaderView::section {\n"
"    background-color: #f1f3f6;\n"
"    border: none;\n"
"}")
        self.table_Volume_Log.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_Volume_Log.setAlternatingRowColors(True)
        self.table_Volume_Log.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_Volume_Log.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_Volume_Log.setShowGrid(False)
        self.table_Volume_Log.setObjectName("table_Volume_Log")
        self.table_Volume_Log.setColumnCount(8)
        self.table_Volume_Log.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_Volume_Log.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Volume_Log.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Volume_Log.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Volume_Log.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.table_Volume_Log.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Volume_Log.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.table_Volume_Log.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        item.setFont(font)
        self.table_Volume_Log.setHorizontalHeaderItem(7, item)
        self.verticalLayout_9.addWidget(self.table_Volume_Log)
        self.verticalLayout_3.addWidget(self.groupBox_Log)
        self.verticalLayout_2.addWidget(self.widget)
        self.stacked_Responsavel.addWidget(self.page_Logistica)
        self.page_Terceiros = QtWidgets.QWidget()
        self.page_Terceiros.setStyleSheet("background-color: #f4f6f9;")
        self.page_Terceiros.setObjectName("page_Terceiros")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_Terceiros)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_3 = QtWidgets.QWidget(self.page_Terceiros)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_51 = QtWidgets.QWidget(self.widget_3)
        self.widget_51.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_51.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_51.setObjectName("widget_51")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.widget_51)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.widget_12 = QtWidgets.QWidget(self.widget_51)
        self.widget_12.setStyleSheet("")
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_46.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_46.setSpacing(3)
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.label_73 = QtWidgets.QLabel(self.widget_12)
        self.label_73.setMinimumSize(QtCore.QSize(0, 0))
        self.label_73.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_73.setFont(font)
        self.label_73.setStyleSheet("border: none;\n"
"background: transparent;\n"
"color: #5f6b7a;\n"
"font-size: 9px;\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.label_73.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_73.setObjectName("label_73")
        self.verticalLayout_46.addWidget(self.label_73)
        self.combo_Tipo_Emb_Ter = QtWidgets.QComboBox(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_Tipo_Emb_Ter.sizePolicy().hasHeightForWidth())
        self.combo_Tipo_Emb_Ter.setSizePolicy(sizePolicy)
        self.combo_Tipo_Emb_Ter.setMinimumSize(QtCore.QSize(0, 25))
        self.combo_Tipo_Emb_Ter.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.combo_Tipo_Emb_Ter.setFont(font)
        self.combo_Tipo_Emb_Ter.setStyleSheet("#combo_Tipo_Emb_Ter {\n"
"    border: 1px solid #e5e7eb;\n"
"    border-radius: 6px;\n"
"    padding-left: 10px;\n"
"    background: white;\n"
"    font-size: 11px;\n"
"    color: #374151;\n"
"}")
        self.combo_Tipo_Emb_Ter.setObjectName("combo_Tipo_Emb_Ter")
        self.verticalLayout_46.addWidget(self.combo_Tipo_Emb_Ter)
        self.horizontalLayout_33.addWidget(self.widget_12)
        self.widget_52 = QtWidgets.QWidget(self.widget_51)
        self.widget_52.setStyleSheet("")
        self.widget_52.setObjectName("widget_52")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout(self.widget_52)
        self.verticalLayout_47.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_47.setSpacing(3)
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.label_85 = QtWidgets.QLabel(self.widget_52)
        self.label_85.setMinimumSize(QtCore.QSize(0, 0))
        self.label_85.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_85.setFont(font)
        self.label_85.setStyleSheet("border: none;\n"
"background: transparent;\n"
"color: #5f6b7a;\n"
"font-size: 9px;\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.label_85.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_85.setObjectName("label_85")
        self.verticalLayout_47.addWidget(self.label_85)
        self.line_Peso_Emb_Ter = QtWidgets.QLineEdit(self.widget_52)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_Peso_Emb_Ter.sizePolicy().hasHeightForWidth())
        self.line_Peso_Emb_Ter.setSizePolicy(sizePolicy)
        self.line_Peso_Emb_Ter.setMinimumSize(QtCore.QSize(0, 25))
        self.line_Peso_Emb_Ter.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.line_Peso_Emb_Ter.setFont(font)
        self.line_Peso_Emb_Ter.setStyleSheet("color: #374151;\n"
"border: none;\n"
"background: white;")
        self.line_Peso_Emb_Ter.setInputMask("")
        self.line_Peso_Emb_Ter.setText("")
        self.line_Peso_Emb_Ter.setFrame(True)
        self.line_Peso_Emb_Ter.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_Peso_Emb_Ter.setAlignment(QtCore.Qt.AlignCenter)
        self.line_Peso_Emb_Ter.setDragEnabled(False)
        self.line_Peso_Emb_Ter.setReadOnly(False)
        self.line_Peso_Emb_Ter.setPlaceholderText("")
        self.line_Peso_Emb_Ter.setObjectName("line_Peso_Emb_Ter")
        self.verticalLayout_47.addWidget(self.line_Peso_Emb_Ter)
        self.horizontalLayout_33.addWidget(self.widget_52)
        self.widget_53 = QtWidgets.QWidget(self.widget_51)
        self.widget_53.setStyleSheet("")
        self.widget_53.setObjectName("widget_53")
        self.verticalLayout_48 = QtWidgets.QVBoxLayout(self.widget_53)
        self.verticalLayout_48.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_48.setSpacing(3)
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.label_86 = QtWidgets.QLabel(self.widget_53)
        self.label_86.setMinimumSize(QtCore.QSize(0, 0))
        self.label_86.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_86.setFont(font)
        self.label_86.setStyleSheet("border: none;\n"
"background: transparent;\n"
"color: #5f6b7a;\n"
"font-size: 9px;\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.label_86.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_86.setObjectName("label_86")
        self.verticalLayout_48.addWidget(self.label_86)
        self.line_Peso_Total_Ter = QtWidgets.QLineEdit(self.widget_53)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_Peso_Total_Ter.sizePolicy().hasHeightForWidth())
        self.line_Peso_Total_Ter.setSizePolicy(sizePolicy)
        self.line_Peso_Total_Ter.setMinimumSize(QtCore.QSize(0, 25))
        self.line_Peso_Total_Ter.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.line_Peso_Total_Ter.setFont(font)
        self.line_Peso_Total_Ter.setStyleSheet("color: #374151;\n"
"border: none;\n"
"background: white;")
        self.line_Peso_Total_Ter.setInputMask("")
        self.line_Peso_Total_Ter.setText("")
        self.line_Peso_Total_Ter.setFrame(True)
        self.line_Peso_Total_Ter.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_Peso_Total_Ter.setAlignment(QtCore.Qt.AlignCenter)
        self.line_Peso_Total_Ter.setDragEnabled(False)
        self.line_Peso_Total_Ter.setReadOnly(False)
        self.line_Peso_Total_Ter.setPlaceholderText("")
        self.line_Peso_Total_Ter.setObjectName("line_Peso_Total_Ter")
        self.verticalLayout_48.addWidget(self.line_Peso_Total_Ter)
        self.horizontalLayout_33.addWidget(self.widget_53)
        self.btn_Add_Vol_Ter = QtWidgets.QPushButton(self.widget_51)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Add_Vol_Ter.sizePolicy().hasHeightForWidth())
        self.btn_Add_Vol_Ter.setSizePolicy(sizePolicy)
        self.btn_Add_Vol_Ter.setMinimumSize(QtCore.QSize(80, 34))
        self.btn_Add_Vol_Ter.setMaximumSize(QtCore.QSize(80, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Add_Vol_Ter.setFont(font)
        self.btn_Add_Vol_Ter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Add_Vol_Ter.setStyleSheet("QPushButton {\n"
"    background-color: #0d4a92;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    min-height: 34px;\n"
"    padding: 0 5px;\n"
"    font-size: 9pt;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1557a6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0a3b75;\n"
"}")
        self.btn_Add_Vol_Ter.setObjectName("btn_Add_Vol_Ter")
        self.horizontalLayout_33.addWidget(self.btn_Add_Vol_Ter)
        self.btn_Excluir_Vol_Ter = QtWidgets.QPushButton(self.widget_51)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Excluir_Vol_Ter.sizePolicy().hasHeightForWidth())
        self.btn_Excluir_Vol_Ter.setSizePolicy(sizePolicy)
        self.btn_Excluir_Vol_Ter.setMinimumSize(QtCore.QSize(80, 34))
        self.btn_Excluir_Vol_Ter.setMaximumSize(QtCore.QSize(80, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Excluir_Vol_Ter.setFont(font)
        self.btn_Excluir_Vol_Ter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Excluir_Vol_Ter.setStyleSheet("QPushButton {\n"
"    background-color: #0d4a92;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    min-height: 34px;\n"
"    padding: 0 5px;\n"
"    font-size: 9pt;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1557a6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0a3b75;\n"
"}")
        self.btn_Excluir_Vol_Ter.setObjectName("btn_Excluir_Vol_Ter")
        self.horizontalLayout_33.addWidget(self.btn_Excluir_Vol_Ter)
        self.verticalLayout_6.addWidget(self.widget_51)
        self.groupBox_Ter = QtWidgets.QGroupBox(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_Ter.setFont(font)
        self.groupBox_Ter.setStyleSheet("#groupBox_Ter {\n"
"    border: none;\n"
"    margin-top: 18px;\n"
"    font-weight: bold;\n"
"    color: #5f6b7a;\n"
"font-size: 9px;\n"
"}\n"
"\n"
"#groupBox_Ter::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 12px;\n"
"    padding: 0 6px 0 6px;\n"
"padding-left: 2px;\n"
"}")
        self.groupBox_Ter.setObjectName("groupBox_Ter")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_Ter)
        self.verticalLayout_13.setContentsMargins(6, 6, 6, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.table_Volume_Ter = QtWidgets.QTableWidget(self.groupBox_Ter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_Volume_Ter.sizePolicy().hasHeightForWidth())
        self.table_Volume_Ter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.table_Volume_Ter.setFont(font)
        self.table_Volume_Ter.setStyleSheet("#table_Volume_Ter {\n"
"    background-color: white;\n"
"    border: 1px solid #e3e6ea;\n"
"    border-radius: 6px;\n"
"    gridline-color: transparent;\n"
"    alternate-background-color: #f8fafc;\n"
"    selection-background-color: #dbe9ff;\n"
"    selection-color: #000000;\n"
"}\n"
"\n"
"QTableWidget#table_Volume_Ter QHeaderView::section {\n"
"    background-color: #f1f3f6;\n"
"    border: none;\n"
"}")
        self.table_Volume_Ter.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_Volume_Ter.setAlternatingRowColors(True)
        self.table_Volume_Ter.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_Volume_Ter.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_Volume_Ter.setShowGrid(False)
        self.table_Volume_Ter.setObjectName("table_Volume_Ter")
        self.table_Volume_Ter.setColumnCount(5)
        self.table_Volume_Ter.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_Volume_Ter.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Volume_Ter.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Volume_Ter.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Volume_Ter.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Volume_Ter.setHorizontalHeaderItem(4, item)
        self.verticalLayout_13.addWidget(self.table_Volume_Ter)
        self.verticalLayout_6.addWidget(self.groupBox_Ter)
        self.verticalLayout_7.addWidget(self.widget_3)
        self.stacked_Responsavel.addWidget(self.page_Terceiros)
        self.page_Maquinas = QtWidgets.QWidget()
        self.page_Maquinas.setStyleSheet("background-color: #f4f6f9;")
        self.page_Maquinas.setObjectName("page_Maquinas")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_Maquinas)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_2 = QtWidgets.QWidget(self.page_Maquinas)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_46 = QtWidgets.QWidget(self.widget_2)
        self.widget_46.setMinimumSize(QtCore.QSize(0, 52))
        self.widget_46.setMaximumSize(QtCore.QSize(16777215, 52))
        self.widget_46.setObjectName("widget_46")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.widget_46)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.widget_11 = QtWidgets.QWidget(self.widget_46)
        self.widget_11.setStyleSheet("")
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_43.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_43.setSpacing(3)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.label_72 = QtWidgets.QLabel(self.widget_11)
        self.label_72.setMinimumSize(QtCore.QSize(0, 0))
        self.label_72.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setStyleSheet("border: none;\n"
"background: transparent;\n"
"color: #5f6b7a;\n"
"font-size: 9px;\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.label_72.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_72.setObjectName("label_72")
        self.verticalLayout_43.addWidget(self.label_72)
        self.combo_Tipo_Emb_Maq = QtWidgets.QComboBox(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_Tipo_Emb_Maq.sizePolicy().hasHeightForWidth())
        self.combo_Tipo_Emb_Maq.setSizePolicy(sizePolicy)
        self.combo_Tipo_Emb_Maq.setMinimumSize(QtCore.QSize(0, 25))
        self.combo_Tipo_Emb_Maq.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.combo_Tipo_Emb_Maq.setFont(font)
        self.combo_Tipo_Emb_Maq.setStyleSheet("#combo_Tipo_Emb_Maq {\n"
"    border: 1px solid #e5e7eb;\n"
"    border-radius: 6px;\n"
"    padding-left: 10px;\n"
"    background: white;\n"
"    font-size: 11px;\n"
"    color: #374151;\n"
"}")
        self.combo_Tipo_Emb_Maq.setObjectName("combo_Tipo_Emb_Maq")
        self.verticalLayout_43.addWidget(self.combo_Tipo_Emb_Maq)
        self.horizontalLayout_30.addWidget(self.widget_11)
        self.widget_47 = QtWidgets.QWidget(self.widget_46)
        self.widget_47.setStyleSheet("")
        self.widget_47.setObjectName("widget_47")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.widget_47)
        self.verticalLayout_44.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_44.setSpacing(3)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.label_83 = QtWidgets.QLabel(self.widget_47)
        self.label_83.setMinimumSize(QtCore.QSize(0, 0))
        self.label_83.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_83.setFont(font)
        self.label_83.setStyleSheet("border: none;\n"
"background: transparent;\n"
"color: #5f6b7a;\n"
"font-size: 9px;\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.label_83.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_83.setObjectName("label_83")
        self.verticalLayout_44.addWidget(self.label_83)
        self.line_Peso_Emb_Maq = QtWidgets.QLineEdit(self.widget_47)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_Peso_Emb_Maq.sizePolicy().hasHeightForWidth())
        self.line_Peso_Emb_Maq.setSizePolicy(sizePolicy)
        self.line_Peso_Emb_Maq.setMinimumSize(QtCore.QSize(0, 25))
        self.line_Peso_Emb_Maq.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.line_Peso_Emb_Maq.setFont(font)
        self.line_Peso_Emb_Maq.setStyleSheet("color: #374151;\n"
"border: none;\n"
"background: white;")
        self.line_Peso_Emb_Maq.setInputMask("")
        self.line_Peso_Emb_Maq.setText("")
        self.line_Peso_Emb_Maq.setFrame(True)
        self.line_Peso_Emb_Maq.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_Peso_Emb_Maq.setAlignment(QtCore.Qt.AlignCenter)
        self.line_Peso_Emb_Maq.setDragEnabled(False)
        self.line_Peso_Emb_Maq.setReadOnly(False)
        self.line_Peso_Emb_Maq.setPlaceholderText("")
        self.line_Peso_Emb_Maq.setObjectName("line_Peso_Emb_Maq")
        self.verticalLayout_44.addWidget(self.line_Peso_Emb_Maq)
        self.horizontalLayout_30.addWidget(self.widget_47)
        self.widget_48 = QtWidgets.QWidget(self.widget_46)
        self.widget_48.setStyleSheet("")
        self.widget_48.setObjectName("widget_48")
        self.verticalLayout_45 = QtWidgets.QVBoxLayout(self.widget_48)
        self.verticalLayout_45.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_45.setSpacing(3)
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.label_84 = QtWidgets.QLabel(self.widget_48)
        self.label_84.setMinimumSize(QtCore.QSize(0, 0))
        self.label_84.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_84.setFont(font)
        self.label_84.setStyleSheet("border: none;\n"
"background: transparent;\n"
"color: #5f6b7a;\n"
"font-size: 9px;\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.label_84.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_84.setObjectName("label_84")
        self.verticalLayout_45.addWidget(self.label_84)
        self.line_Peso_Total_Maq = QtWidgets.QLineEdit(self.widget_48)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_Peso_Total_Maq.sizePolicy().hasHeightForWidth())
        self.line_Peso_Total_Maq.setSizePolicy(sizePolicy)
        self.line_Peso_Total_Maq.setMinimumSize(QtCore.QSize(0, 25))
        self.line_Peso_Total_Maq.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.line_Peso_Total_Maq.setFont(font)
        self.line_Peso_Total_Maq.setStyleSheet("color: #374151;\n"
"border: none;\n"
"background: white;")
        self.line_Peso_Total_Maq.setInputMask("")
        self.line_Peso_Total_Maq.setText("")
        self.line_Peso_Total_Maq.setFrame(True)
        self.line_Peso_Total_Maq.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_Peso_Total_Maq.setAlignment(QtCore.Qt.AlignCenter)
        self.line_Peso_Total_Maq.setDragEnabled(False)
        self.line_Peso_Total_Maq.setReadOnly(False)
        self.line_Peso_Total_Maq.setPlaceholderText("")
        self.line_Peso_Total_Maq.setObjectName("line_Peso_Total_Maq")
        self.verticalLayout_45.addWidget(self.line_Peso_Total_Maq)
        self.horizontalLayout_30.addWidget(self.widget_48)
        self.btn_Add_Vol_Maq = QtWidgets.QPushButton(self.widget_46)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Add_Vol_Maq.sizePolicy().hasHeightForWidth())
        self.btn_Add_Vol_Maq.setSizePolicy(sizePolicy)
        self.btn_Add_Vol_Maq.setMinimumSize(QtCore.QSize(80, 34))
        self.btn_Add_Vol_Maq.setMaximumSize(QtCore.QSize(80, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Add_Vol_Maq.setFont(font)
        self.btn_Add_Vol_Maq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Add_Vol_Maq.setStyleSheet("QPushButton {\n"
"    background-color: #0d4a92;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    min-height: 34px;\n"
"    padding: 0 5px;\n"
"    font-size: 9pt;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1557a6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0a3b75;\n"
"}")
        self.btn_Add_Vol_Maq.setObjectName("btn_Add_Vol_Maq")
        self.horizontalLayout_30.addWidget(self.btn_Add_Vol_Maq)
        self.btn_Excluir_Vol_Maq = QtWidgets.QPushButton(self.widget_46)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Excluir_Vol_Maq.sizePolicy().hasHeightForWidth())
        self.btn_Excluir_Vol_Maq.setSizePolicy(sizePolicy)
        self.btn_Excluir_Vol_Maq.setMinimumSize(QtCore.QSize(80, 34))
        self.btn_Excluir_Vol_Maq.setMaximumSize(QtCore.QSize(80, 38))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Excluir_Vol_Maq.setFont(font)
        self.btn_Excluir_Vol_Maq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Excluir_Vol_Maq.setStyleSheet("QPushButton {\n"
"    background-color: #0d4a92;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    min-height: 34px;\n"
"    padding: 0 5px;\n"
"    font-size: 9pt;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1557a6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0a3b75;\n"
"}")
        self.btn_Excluir_Vol_Maq.setObjectName("btn_Excluir_Vol_Maq")
        self.horizontalLayout_30.addWidget(self.btn_Excluir_Vol_Maq)
        self.verticalLayout_4.addWidget(self.widget_46)
        self.groupBox_Maq = QtWidgets.QGroupBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_Maq.setFont(font)
        self.groupBox_Maq.setStyleSheet("#groupBox_Maq {\n"
"    border: none;\n"
"    margin-top: 18px;\n"
"    font-weight: bold;\n"
"    color: #5f6b7a;\n"
"font-size: 9px;\n"
"}\n"
"\n"
"#groupBox_Maq::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 12px;\n"
"    padding: 0 6px 0 6px;\n"
"padding-left: 2px;\n"
"}")
        self.groupBox_Maq.setObjectName("groupBox_Maq")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_Maq)
        self.verticalLayout_11.setContentsMargins(6, 6, 6, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.table_Volume_Maq = QtWidgets.QTableWidget(self.groupBox_Maq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_Volume_Maq.sizePolicy().hasHeightForWidth())
        self.table_Volume_Maq.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.table_Volume_Maq.setFont(font)
        self.table_Volume_Maq.setStyleSheet("#table_Volume_Maq {\n"
"    background-color: white;\n"
"    border: 1px solid #e3e6ea;\n"
"    border-radius: 6px;\n"
"    gridline-color: transparent;\n"
"    alternate-background-color: #f8fafc;\n"
"    selection-background-color: #dbe9ff;\n"
"    selection-color: #000000;\n"
"}\n"
"\n"
"QTableWidget#table_Volume_Maq QHeaderView::section {\n"
"    background-color: #f1f3f6;\n"
"    border: none;\n"
"}")
        self.table_Volume_Maq.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_Volume_Maq.setAlternatingRowColors(True)
        self.table_Volume_Maq.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_Volume_Maq.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_Volume_Maq.setShowGrid(False)
        self.table_Volume_Maq.setObjectName("table_Volume_Maq")
        self.table_Volume_Maq.setColumnCount(5)
        self.table_Volume_Maq.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_Volume_Maq.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Volume_Maq.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Volume_Maq.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Volume_Maq.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Volume_Maq.setHorizontalHeaderItem(4, item)
        self.verticalLayout_11.addWidget(self.table_Volume_Maq)
        self.verticalLayout_4.addWidget(self.groupBox_Maq)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.stacked_Responsavel.addWidget(self.page_Maquinas)
        self.verticalLayout.addWidget(self.stacked_Responsavel)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout.addWidget(self.frame_5)
        self.widget_14 = QtWidgets.QWidget(self.centralwidget)
        self.widget_14.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_14.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_14.setStyleSheet("background-color: #f4f6f9;")
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_25 = QtWidgets.QWidget(self.widget_14)
        self.widget_25.setStyleSheet("")
        self.widget_25.setObjectName("widget_25")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.widget_25)
        self.verticalLayout_23.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_23.setSpacing(3)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_67 = QtWidgets.QLabel(self.widget_25)
        self.label_67.setMinimumSize(QtCore.QSize(0, 0))
        self.label_67.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setStyleSheet("border: none;\n"
"background: transparent;\n"
"color: #5f6b7a;\n"
"font-size: 9px;\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.label_67.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_67.setObjectName("label_67")
        self.verticalLayout_23.addWidget(self.label_67)
        self.line_Peso_Bruto = QtWidgets.QLineEdit(self.widget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_Peso_Bruto.sizePolicy().hasHeightForWidth())
        self.line_Peso_Bruto.setSizePolicy(sizePolicy)
        self.line_Peso_Bruto.setMinimumSize(QtCore.QSize(0, 25))
        self.line_Peso_Bruto.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.line_Peso_Bruto.setFont(font)
        self.line_Peso_Bruto.setStyleSheet("color: #374151;\n"
"border: none;\n"
"background: white;")
        self.line_Peso_Bruto.setInputMask("")
        self.line_Peso_Bruto.setText("")
        self.line_Peso_Bruto.setFrame(True)
        self.line_Peso_Bruto.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_Peso_Bruto.setAlignment(QtCore.Qt.AlignCenter)
        self.line_Peso_Bruto.setDragEnabled(False)
        self.line_Peso_Bruto.setReadOnly(True)
        self.line_Peso_Bruto.setPlaceholderText("")
        self.line_Peso_Bruto.setObjectName("line_Peso_Bruto")
        self.verticalLayout_23.addWidget(self.line_Peso_Bruto)
        self.horizontalLayout_8.addWidget(self.widget_25)
        self.widget_26 = QtWidgets.QWidget(self.widget_14)
        self.widget_26.setStyleSheet("")
        self.widget_26.setObjectName("widget_26")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.widget_26)
        self.verticalLayout_24.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_24.setSpacing(3)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_68 = QtWidgets.QLabel(self.widget_26)
        self.label_68.setMinimumSize(QtCore.QSize(0, 0))
        self.label_68.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setStyleSheet("border: none;\n"
"background: transparent;\n"
"color: #5f6b7a;\n"
"font-size: 9px;\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.label_68.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_68.setObjectName("label_68")
        self.verticalLayout_24.addWidget(self.label_68)
        self.line_Peso_Liquido = QtWidgets.QLineEdit(self.widget_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_Peso_Liquido.sizePolicy().hasHeightForWidth())
        self.line_Peso_Liquido.setSizePolicy(sizePolicy)
        self.line_Peso_Liquido.setMinimumSize(QtCore.QSize(0, 25))
        self.line_Peso_Liquido.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.line_Peso_Liquido.setFont(font)
        self.line_Peso_Liquido.setStyleSheet("color: #374151;\n"
"border: none;\n"
"background: white;")
        self.line_Peso_Liquido.setInputMask("")
        self.line_Peso_Liquido.setText("")
        self.line_Peso_Liquido.setFrame(True)
        self.line_Peso_Liquido.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_Peso_Liquido.setAlignment(QtCore.Qt.AlignCenter)
        self.line_Peso_Liquido.setDragEnabled(False)
        self.line_Peso_Liquido.setReadOnly(True)
        self.line_Peso_Liquido.setPlaceholderText("")
        self.line_Peso_Liquido.setObjectName("line_Peso_Liquido")
        self.verticalLayout_24.addWidget(self.line_Peso_Liquido)
        self.horizontalLayout_8.addWidget(self.widget_26)
        self.widget_15 = QtWidgets.QWidget(self.widget_14)
        self.widget_15.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_15.setMaximumSize(QtCore.QSize(100, 16777215))
        self.widget_15.setStyleSheet("")
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_26.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_26.setSpacing(3)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_69 = QtWidgets.QLabel(self.widget_15)
        self.label_69.setMinimumSize(QtCore.QSize(0, 0))
        self.label_69.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setStyleSheet("border: none;\n"
"background: transparent;\n"
"color: #5f6b7a;\n"
"font-size: 9px;\n"
"font-weight: bold;\n"
"padding-left: 2px;")
        self.label_69.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_69.setObjectName("label_69")
        self.verticalLayout_26.addWidget(self.label_69)
        self.spin_Volume = QtWidgets.QSpinBox(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_Volume.sizePolicy().hasHeightForWidth())
        self.spin_Volume.setSizePolicy(sizePolicy)
        self.spin_Volume.setMinimumSize(QtCore.QSize(0, 25))
        self.spin_Volume.setMaximumSize(QtCore.QSize(16777215, 25))
        self.spin_Volume.setStyleSheet("color: #374151;\n"
"border: none;\n"
"background: white;\n"
"font-size: 11px;")
        self.spin_Volume.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_Volume.setReadOnly(True)
        self.spin_Volume.setObjectName("spin_Volume")
        self.verticalLayout_26.addWidget(self.spin_Volume)
        self.horizontalLayout_8.addWidget(self.widget_15)
        self.btn_Salvar = QtWidgets.QPushButton(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Salvar.sizePolicy().hasHeightForWidth())
        self.btn_Salvar.setSizePolicy(sizePolicy)
        self.btn_Salvar.setMinimumSize(QtCore.QSize(90, 40))
        self.btn_Salvar.setMaximumSize(QtCore.QSize(90, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Salvar.setFont(font)
        self.btn_Salvar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Salvar.setStyleSheet("QPushButton {\n"
"    background-color: #0d4a92;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 0 5px;\n"
"    font-size: 10pt;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1557a6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0a3b75;\n"
"}")
        self.btn_Salvar.setObjectName("btn_Salvar")
        self.horizontalLayout_8.addWidget(self.btn_Salvar)
        self.verticalLayout.addWidget(self.widget_14)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stacked_Responsavel.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Projetos Engenharia"))
        self.label_13.setText(_translate("MainWindow", "VOLUMES"))
        self.label_75.setText(_translate("MainWindow", "📦  TIPO EMBALAGEM"))
        self.label_82.setText(_translate("MainWindow", "⚖️  PESO EMBALAGEM (KG)"))
        self.label_87.setText(_translate("MainWindow", "⚖️  PESO TOTAL (KG)"))
        self.btn_Add_Vol_Log.setText(_translate("MainWindow", "Adicionar\n"
"Volume"))
        self.btn_Excluir_Vol_Log.setText(_translate("MainWindow", "Excluir\n"
"Volume"))
        self.label_93.setText(_translate("MainWindow", "📦  ALTURA (MM)"))
        self.label_95.setText(_translate("MainWindow", "⚖️  LARGURA (MM)"))
        self.label_96.setText(_translate("MainWindow", "⚖️  COMPRIMENTO (MM)"))
        self.groupBox_Log.setTitle(_translate("MainWindow", "VOLUMES"))
        item = self.table_Volume_Log.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "VOLUME"))
        item = self.table_Volume_Log.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ALTURA"))
        item = self.table_Volume_Log.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "LARGURA"))
        item = self.table_Volume_Log.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "COMPR."))
        item = self.table_Volume_Log.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "TIPO"))
        item = self.table_Volume_Log.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "PESO EMB."))
        item = self.table_Volume_Log.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "PESO TOTAL"))
        item = self.table_Volume_Log.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "PESO LIQ."))
        self.label_73.setText(_translate("MainWindow", "📦  TIPO EMBALAGEM"))
        self.label_85.setText(_translate("MainWindow", "⚖️  PESO EMBALAGEM (KG)"))
        self.label_86.setText(_translate("MainWindow", "⚖️  PESO TOTAL (KG)"))
        self.btn_Add_Vol_Ter.setText(_translate("MainWindow", "Adicionar\n"
"Volume"))
        self.btn_Excluir_Vol_Ter.setText(_translate("MainWindow", "Excluir\n"
"Volume"))
        self.groupBox_Ter.setTitle(_translate("MainWindow", "VOLUMES"))
        item = self.table_Volume_Ter.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "VOLUME"))
        item = self.table_Volume_Ter.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TIPO"))
        item = self.table_Volume_Ter.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PESO EMB."))
        item = self.table_Volume_Ter.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PESO TOTAL"))
        item = self.table_Volume_Ter.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "PESO LIQ."))
        self.label_72.setText(_translate("MainWindow", "📦  TIPO EMBALAGEM"))
        self.label_83.setText(_translate("MainWindow", "⚖️  PESO EMBALAGEM (KG)"))
        self.label_84.setText(_translate("MainWindow", "⚖️  PESO TOTAL (KG)"))
        self.btn_Add_Vol_Maq.setText(_translate("MainWindow", "Adicionar\n"
"Volume"))
        self.btn_Excluir_Vol_Maq.setText(_translate("MainWindow", "Excluir\n"
"Volume"))
        self.groupBox_Maq.setTitle(_translate("MainWindow", "VOLUMES"))
        item = self.table_Volume_Maq.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "VOLUME"))
        item = self.table_Volume_Maq.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TIPO"))
        item = self.table_Volume_Maq.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PESO EMB."))
        item = self.table_Volume_Maq.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PESO TOTAL"))
        item = self.table_Volume_Maq.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "PESO LIQ."))
        self.label_67.setText(_translate("MainWindow", "⚖️  PESO BRUTO (KG)"))
        self.label_68.setText(_translate("MainWindow", "⚖️  PESO LÍQUIDO (KG)"))
        self.label_69.setText(_translate("MainWindow", "📦  VOLUME"))
        self.btn_Salvar.setText(_translate("MainWindow", "Salvar"))
